### ISSUE TITLE
Update and Improve Project Status View

### ISSUE THREAD

**Issue by snehara99** [microsoft/vscode-cmake-tools#3291]
### Brief Issue Summary

We are planning to make the Project Status View more robust with an updated UI with pinnable commands and a new tasks view. Please feel free to leave thoughts and suggestions for the updated view in this thread, thanks!

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-cmake-tools/issues/3295
- [ ] https://github.com/microsoft/vscode-cmake-tools/issues/3402
- [ ] https://github.com/microsoft/vscode-cmake-tools/issues/3297
- [ ] https://github.com/microsoft/vscode-cmake-tools/issues/1582
- [ ] https://github.com/microsoft/vscode-cmake-tools/issues/3299
- [ ] https://github.com/microsoft/vscode-cmake-tools/issues/3386
- [ ] https://github.com/microsoft/vscode-cmake-tools/issues/3452
```

**Comment by H-G-Hristov** [comment]
It would be great if cmake tools integrates better with cpp and there are no duplicated commands and also that the experience is more standardized.
