### ISSUE TITLE
Update and improve Side Bar

### ISSUE THREAD

**Issue by snehara99** [microsoft/vscode-cmake-tools#3294]
This work item is to track all of the tasks that are under improving the CMake Tools Side Bar
```[tasklist]
### Tasks
- [ ] Decide on best UI framework
- [ ] Implement status bar commands in Project Status View
- [ ] Allow pinning of Project Status View commands in status bar
- [ ] Allow shortcuts of other CMake Tools commands in Side Bar
- [ ] Implement tasks into the Side Bar
```
